model_provider = "custom"
model = "gpt-5.6-sol"
model_reasoning_effort = "high"
disable_response_storage = true
notify = ['C:\Users\win\AppData\Local\OpenAI\Codex\runtimes\cua_node\a89897d3d9baa117\bin\node_modules\@oai\sky\bin\windows\codex-computer-use.exe', "turn-ended"]

[model_providers.custom]
name = "One-API"
base_url = "https://api.tangguo.xin/v1"
wire_api = "responses"
requires_openai_auth = true
experimental_bearer_token = "sk-YOUR_SECRET"

[desktop]
followUpQueueMode = "queue"
conversationDetailMode = "STEPS_COMMANDS"

[desktop.open-in-target-preferences]
global = "cursor"

[desktop.open-in-target-preferences.perPath]
'C:\Users\win\Desktop\敖钦储能项目' = "fileManager"
'C:\Users\win\Desktop\AI--main' = "cursor"

[windows]
sandbox = "elevated"

[projects.'c:\users\win\desktop\敖钦储能项目']
trust_level = "trusted"

[projects.'c:\users\win\desktop\program1-main-latest']
trust_level = "trusted"

[projects.'c:\users\win\desktop\ai--main']
trust_level = "trusted"

[projects.'c:\users\win\documents\codex\2026-07-10\codex-5-6-5-6-codex']
trust_level = "trusted"

[projects.'c:\users\win\desktop\yinpinjianting']
trust_level = "trusted"

[projects.'c:\users\win\documents\codex\2026-07-16\du']
trust_level = "trusted"

[projects.'c:\users\win\desktop\产能评价']
trust_level = "trusted"

[projects.'c:\users\win\documents\codex\2026-07-17\new-chat']
trust_level = "trusted"

[projects.'c:\users\win\documents\codex\2026-07-17\ai-ai-agent']
trust_level = "trusted"

[plugins."superpowers@openai-api-curated"]
enabled = true

[plugins."hyperframes@openai-api-curated"]
enabled = true

[plugins."github@openai-api-curated"]
enabled = true

[plugins."chrome@openai-bundled"]
enabled = true

[plugins."computer-use@openai-bundled"]
enabled = true

[plugins."product-design@openai-curated-remote"]
enabled = true

[plugins."creative-production@openai-curated-remote"]
enabled = true

[plugins."picsart@openai-curated"]
enabled = true

[plugins."github@openai-curated"]
enabled = true

[plugins."superpowers@openai-curated"]
enabled = true

[plugins."supabase@openai-curated"]
enabled = true

[plugins."documents@openai-primary-runtime"]
enabled = true

[plugins."pdf@openai-primary-runtime"]
enabled = true

[plugins."spreadsheets@openai-primary-runtime"]
enabled = true

[plugins."presentations@openai-primary-runtime"]
enabled = true

[plugins."template-creator@openai-primary-runtime"]
enabled = true

[marketplaces]

[marketplaces.openai-curated]
source_type = "local"
source = '\\?\C:\Users\win\.codex\.tmp\plugins'

[marketplaces.openai-api-curated]
source_type = "local"
source = '\\?\C:\Users\win\.codex\.tmp\plugins'

[marketplaces.openai-curated-remote]
source_type = "local"
source = '\\?\C:\Users\win\.codex\.tmp\plugins-remote'

[marketplaces.openai-bundled]
source_type = "local"
source = '\\?\C:\Users\win\.codex\.tmp\bundled-marketplaces\openai-bundled'

[marketplaces.openai-primary-runtime]
last_updated = "2026-07-16T09:15:49Z"
source_type = "local"
source = '\\?\C:\Users\win\.cache\codex-runtimes\codex-primary-runtime\plugins\openai-primary-runtime'

[features]

[mcp_servers]

[mcp_servers.chrome-devtools]
type = "stdio"
command = "npx"
args = ["-y", "chrome-devtools-mcp@latest"]
startup_timeout_sec = 30

[mcp_servers.context7]
type = "stdio"
command = "npx"
args = ["-y", "@upstash/context7-mcp@latest"]
startup_timeout_sec = 30

[mcp_servers.exa]
type = "stdio"
command = "npx"
args = ["-y", "mcp-remote", "https://mcp.exa.ai/mcp"]
startup_timeout_sec = 30

[mcp_servers.fal-ai]
type = "stdio"
command = "npx"
args = ["-y", "fal-ai-mcp-server"]
startup_timeout_sec = 30

[mcp_servers.filesystem-agent-platform]
type = "stdio"
command = "npx"
args = ["-y", "@modelcontextprotocol/server-filesystem", 'C:\Users\win\Desktop\Agent Platform']
startup_timeout_sec = 30

[mcp_servers.github]
type = "stdio"
command = "npx"
args = ["-y", "@modelcontextprotocol/server-github"]
startup_timeout_sec = 30

[mcp_servers.memory]
type = "stdio"
command = "npx"
args = ["-y", "@modelcontextprotocol/server-memory"]
startup_timeout_sec = 30

[mcp_servers.node_repl]
type = "stdio"
command = 'C:\Users\win\AppData\Local\OpenAI\Codex\bin\34ab3e1324cc55b5\node_repl.exe'
startup_timeout_sec = 120

[mcp_servers.node_repl.env]
BROWSER_USE_AVAILABLE_BACKENDS = "chrome,iab"
BROWSER_USE_CODEX_APP_BUILD_FLAVOR = "prod"
CODEX_CLI_PATH = 'C:\Users\win\AppData\Local\OpenAI\Codex\bin\716dda49c14d31a0\codex.exe'
CODEX_HOME = 'C:\Users\win\.codex'
NODE_REPL_INSTRUCTIONS_USE_CASE_BROWSER = "Control the in-app browser in conjunction with the Browser Plugin."
NODE_REPL_INSTRUCTIONS_USE_CASE_CHROME = "Control the Chrome browser in conjunction with the Chrome Plugin. Prefer this method of controlling Chrome over alternatives (such as Computer Use) unless the user explicitly mentions an alternative."
NODE_REPL_NATIVE_PIPE_CONNECT_TIMEOUT_MS = "1000"
NODE_REPL_NODE_MODULE_DIRS = ""
NODE_REPL_NODE_PATH = 'C:\Users\win\AppData\Local\OpenAI\Codex\bin\5b9024f90663758b\node.exe'
NODE_REPL_TRUSTED_BROWSER_CLIENT_SHA256S = "0b0d41e7a14a4903d2f95b0b3f427ed796b12c8edca2fa392a03df43997075ae,e13c388c2427308a68dffc803e1f28316077b719672e4518a621ae6ab56ad7cf"
NODE_REPL_TRUSTED_CODE_PATHS = 'C:\Users\win\.codex'

[mcp_servers.playwright]
type = "stdio"
command = "npx"
args = ["-y", "@playwright/mcp@latest", "--browser", "chrome"]
startup_timeout_sec = 30

[mcp_servers.sequential-thinking]
type = "stdio"
command = "npx"
args = ["-y", "@modelcontextprotocol/server-sequential-thinking"]
startup_timeout_sec = 30
