"""Unified platform data contracts (single source of truth for all layers).

Import from here, never redefine these shapes inside a service:

    from shared.models import OHLCVBar, BacktestReport, RiskEvent
"""

from __future__ import annotations

from .alpha import AlphaOperator, AlphaPlan
from .api import ApiError, CollectionResponse, TaskSubmission
from .backtest import (
    GATE_MAX_DRAWDOWN,
    GATE_MIN_EXPECTANCY,
    GATE_MIN_PROFIT_FACTOR,
    GATE_MIN_SHARPE,
    BacktestReport,
    GateDecision,
)
from .base import PlatformModel
from .decision_memory import DecisionMemoryEntry
from .enums import (
    BacktestEngine,
    BetDecision,
    EnsembleStatus,
    Exchange,
    Market,
    OrderType,
    RiskEventType,
    RiskLevel,
    RiskResolutionStatus,
    RiskSeverity,
    RunStatus,
    StrategyStatus,
    Timeframe,
    TradeSide,
    TripleBarrierOutcome,
)
from .execution_runtime import (
    BinanceTestnetAccountStatus,
    BinanceTestnetOrderView,
    BinanceTestnetPositionView,
    ExchangeAccountSnapshot,
    ExchangeGatewayCapability,
    ReconciliationRecord,
    TradingRuntimeStatus,
)
from .macro import MacroEvent
from .market import (
    ConsoleOverview,
    ExchangeCapability,
    FundingArbitrageSignal,
    MarketExtras,
    MarketOrderBookResponse,
    MarketSnapshot,
    MarketTrade,
    MarketTradesResponse,
    MarketUniverseItem,
    OHLCVBar,
    OhlcvSeriesResponse,
    OrderBookLevel,
    UniverseAsset,
)
from .market_intelligence import (
    MAX_MARKET_INTELLIGENCE_VOTE_WEIGHT,
    MarketEvent,
    MarketIntelligenceFeatureSnapshot,
    MarketIntelligenceProviderStatus,
    MarketIntelligenceSignal,
)
from .playbook import (
    DecisionStage,
    ExitRule,
    ExternalStrategySource,
    LlmRagBoundary,
    OptimizationRoadmapItem,
    PlaybookMetadata,
    PositionSizingPolicy,
    RoadmapAuditEntry,
    RoadmapStatus,
    RoadmapUpdate,
    ScopedDefault,
    StrategyChannel,
    StrategyPlaybook,
    TechnicalSignalDefinition,
)
from .research_source import (
    ResearchSourceAsset,
    ResearchSourceIdeaExtractionRequest,
    ResearchSourceImportRequest,
    ResearchSourceImportResult,
    StrategySourceManifest,
)
from .risk import RiskEvent, RiskEventResolutionUpdate, RiskProfile, RiskProfileUpdate
from .signal import (
    CandidateSignalSeries,
    DecisionVetoResult,
    MetaLabel,
    MetaLabelRequest,
    MetaLabelSample,
    SignalEnsemble,
    SignalEnsembleRequest,
    SignalVote,
    TradeSignal,
)
from .strategy import (
    StrategyBase,
    StrategyContract,
    StrategyCreate,
    StrategyDraft,
    StrategyIdea,
    StrategyRead,
    StrategyRules,
    StrategyUpdate,
    StrategyVersion,
)
from .validation import HypothesisRecord, PodRiskReport, ValidationBenchmarkResult
from .workflow import (
    AdjustLeverageRequest,
    AgentTask,
    AgentTaskRequest,
    AssetRiskTierSettings,
    AutoTradingSettings,
    BacktestRun,
    BacktestSubmissionRequest,
    CancelOrderRequest,
    CarryBacktestRequest,
    CarryExecutionLegResult,
    CarryExecutionRequest,
    CarryExecutionStatus,
    ClosePositionRequest,
    ExecutionOrderRequest,
    ExecutionRiskState,
    ExecutionSignal,
    FailureRecord,
    IngestionJob,
    IngestionJobRequest,
    LeverageAdjustmentResult,
    LiveRun,
    LiveRunRequest,
    LLMProviderStatus,
    LLMStatusResponse,
    ManualOrderRequest,
    ManualTradingContext,
    NotificationDeliveryUpdate,
    NotificationOutboxItem,
    OptimizationRun,
    OptimizationSubmissionRequest,
    OrderExecution,
    PaperRun,
    PaperRunRequest,
    PaperRunStatusUpdate,
    PaperRunStepRequest,
    PaperRuntimeAction,
    PaperRuntimeCycleRequest,
    PaperRuntimeCycleResult,
    PaperRuntimeStatus,
    PositionSnapshot,
    ReviewReport,
    TestnetAcceptanceOrderEvidence,
    TestnetAcceptanceRunRequest,
    TestnetAcceptanceRunResult,
    TestnetAcceptanceRunStatus,
    TestnetAcceptanceSymbolResult,
)

__all__ = [
    # base
    "PlatformModel",
    # enums
    "BacktestEngine",
    "Exchange",
    "Market",
    "RiskEventType",
    "RiskLevel",
    "RiskResolutionStatus",
    "RiskSeverity",
    "RunStatus",
    "StrategyStatus",
    "Timeframe",
    "TradeSide",
    "OrderType",
    "EnsembleStatus",
    "BetDecision",
    "TripleBarrierOutcome",
    # market
    "OHLCVBar",
    "MarketExtras",
    "MarketSnapshot",
    "OhlcvSeriesResponse",
    "OrderBookLevel",
    "MarketOrderBookResponse",
    "MarketTrade",
    "MarketTradesResponse",
    "ConsoleOverview",
    "ExchangeCapability",
    "MarketUniverseItem",
    "UniverseAsset",
    "FundingArbitrageSignal",
    "MAX_MARKET_INTELLIGENCE_VOTE_WEIGHT",
    "MarketEvent",
    "MarketIntelligenceFeatureSnapshot",
    "MarketIntelligenceProviderStatus",
    "MarketIntelligenceSignal",
    "PlaybookMetadata",
    "StrategyChannel",
    "DecisionStage",
    "TechnicalSignalDefinition",
    "ExitRule",
    "ScopedDefault",
    "PositionSizingPolicy",
    "LlmRagBoundary",
    "ExternalStrategySource",
    "RoadmapAuditEntry",
    "RoadmapStatus",
    "RoadmapUpdate",
    "OptimizationRoadmapItem",
    "StrategyPlaybook",
    # backtest
    "BacktestReport",
    "GateDecision",
    "GATE_MIN_SHARPE",
    "GATE_MIN_PROFIT_FACTOR",
    "GATE_MAX_DRAWDOWN",
    "GATE_MIN_EXPECTANCY",
    "HypothesisRecord",
    "ValidationBenchmarkResult",
    "PodRiskReport",
    # risk
    "RiskEvent",
    "RiskEventResolutionUpdate",
    "RiskProfile",
    "RiskProfileUpdate",
    "StrategySourceManifest",
    "ResearchSourceAsset",
    "ResearchSourceImportRequest",
    "ResearchSourceIdeaExtractionRequest",
    "ResearchSourceImportResult",
    # macro
    "MacroEvent",
    # signal
    "TradeSignal",
    "CandidateSignalSeries",
    "SignalVote",
    "SignalEnsemble",
    "SignalEnsembleRequest",
    "DecisionVetoResult",
    "MetaLabel",
    "MetaLabelSample",
    "MetaLabelRequest",
    # alpha
    "AlphaOperator",
    "AlphaPlan",
    # api
    "CollectionResponse",
    "TaskSubmission",
    "ApiError",
    # strategy
    "StrategyIdea",
    "StrategyDraft",
    "StrategyVersion",
    "StrategyBase",
    "StrategyContract",
    "StrategyCreate",
    "StrategyUpdate",
    "StrategyRead",
    "StrategyRules",
    "DecisionMemoryEntry",
    "ExchangeGatewayCapability",
    "ExchangeAccountSnapshot",
    "ReconciliationRecord",
    "TradingRuntimeStatus",
    "BinanceTestnetAccountStatus",
    "BinanceTestnetOrderView",
    "BinanceTestnetPositionView",
    # workflow
    "BacktestRun",
    "BacktestSubmissionRequest",
    "CarryBacktestRequest",
    "OptimizationRun",
    "OptimizationSubmissionRequest",
    "PaperRun",
    "AssetRiskTierSettings",
    "AutoTradingSettings",
    "PaperRuntimeAction",
    "PaperRuntimeCycleRequest",
    "PaperRuntimeCycleResult",
    "PaperRuntimeStatus",
    "TestnetAcceptanceOrderEvidence",
    "TestnetAcceptanceRunRequest",
    "TestnetAcceptanceRunResult",
    "TestnetAcceptanceRunStatus",
    "TestnetAcceptanceSymbolResult",
    "PaperRunRequest",
    "PaperRunStatusUpdate",
    "PaperRunStepRequest",
    "LiveRun",
    "LiveRunRequest",
    "ExecutionSignal",
    "ExecutionRiskState",
    "ExecutionOrderRequest",
    "ManualOrderRequest",
    "ManualTradingContext",
    "ClosePositionRequest",
    "AdjustLeverageRequest",
    "CancelOrderRequest",
    "CarryExecutionLegResult",
    "CarryExecutionRequest",
    "CarryExecutionStatus",
    "LeverageAdjustmentResult",
    "OrderExecution",
    "PositionSnapshot",
    "ReviewReport",
    "FailureRecord",
    "IngestionJob",
    "IngestionJobRequest",
    "AgentTask",
    "AgentTaskRequest",
    "NotificationDeliveryUpdate",
    "NotificationOutboxItem",
    "LLMProviderStatus",
    "LLMStatusResponse",
]
