# Scans skills/ under the nearest project root and writes skills-index.md files.
param(
    [ValidateSet('Cursor', 'Claude', 'Codex', 'Plain')]
    [string]$OutputFormat = 'Plain',
    [ValidateSet('SessionStart', 'UserPromptSubmit', 'Plain')]
    [string]$HookEvent = 'Plain',
    [string]$StartDir = ''
)

$ErrorActionPreference = 'Stop'

$excludePathPattern = '(\\|/)(agency-agents-main|\.claude|\.codex|\.gemini|\.continue|\.factory|\.hermes|\.kiro|\.mastracode|\.opencode|\.codebuddy|\.pi|\.cursor)(\\|/)'

function Get-FrontmatterYaml {
    param([string]$Content)
    if ($Content -match '(?ms)^---\s*\r?\n(.*?)\r?\n---') {
        return $Matches[1]
    }
    return $null
}

function Get-FrontmatterField {
    param([string]$Content, [string]$Field)
    $yaml = Get-FrontmatterYaml -Content $Content
    if (-not $yaml) { return $null }
    if ($yaml -match "(?m)^${Field}:\s*\|\s*$") {
        $start = $Matches[0]
        $rest = $yaml.Substring($yaml.IndexOf($start) + $start.Length)
        $lines = @()
        foreach ($line in ($rest -split "`r?`n")) {
            if ($line -match '^\S') { break }
            if ($line -match '^(\s+)(.*)$') { $lines += $Matches[2].TrimEnd() }
            elseif ($line.Trim() -eq '') { $lines += '' }
            else { break }
        }
        return (($lines -join ' ').Trim())
    }
    if ($yaml -match "(?m)^${Field}:\s*['""](.+?)['""]\s*$") {
        return $Matches[1].Trim()
    }
    if ($yaml -match "(?m)^${Field}:\s*(.+)$") {
        return $Matches[1].Trim().Trim('"').Trim("'")
    }
    return $null
}

function Find-ProjectRootWithSkills {
    param([string]$SeedDir)

    $candidates = @()
    if ($SeedDir) { $candidates += $SeedDir }
    if ($env:CLAUDE_PROJECT_DIR) { $candidates += $env:CLAUDE_PROJECT_DIR }
    if ($env:CURSOR_PROJECT_DIR) { $candidates += $env:CURSOR_PROJECT_DIR }
    if ($env:CODEX_PROJECT_DIR) { $candidates += $env:CODEX_PROJECT_DIR }
    $candidates += (Get-Location).Path

    $seen = @{}
    foreach ($start in $candidates) {
        if ([string]::IsNullOrWhiteSpace($start)) { continue }
        $dir = (Resolve-Path -LiteralPath $start -ErrorAction SilentlyContinue).Path
        if (-not $dir) { $dir = $start }
        while ($dir) {
            if ($seen.ContainsKey($dir)) { break }
            $seen[$dir] = $true
            $skillsRoot = Join-Path $dir 'skills'
            if (Test-Path $skillsRoot) {
                $hasSkill = Get-ChildItem -Path $skillsRoot -Filter 'SKILL.md' -Recurse -File -ErrorAction SilentlyContinue |
                    Where-Object { $_.FullName -notmatch $excludePathPattern } |
                    Select-Object -First 1
                if ($hasSkill) { return $dir }
            }
            $parent = Split-Path $dir -Parent
            if (-not $parent -or $parent -eq $dir) { break }
            $dir = $parent
        }
    }
    return $null
}

function Write-SkillsIndex {
    param(
        [string]$ProjectRoot,
        [array]$Items,
        [string]$IndexPath,
        [string]$GeneratorLabel
    )
    $indexDir = Split-Path $IndexPath -Parent
    if (-not (Test-Path $indexDir)) {
        New-Item -ItemType Directory -Path $indexDir -Force | Out-Null
    }
    $lines = @(
        '# Project Skills Index',
        '',
        "> Auto-generated by $GeneratorLabel. Do not edit by hand.",
        "> Last updated: $(Get-Date -Format 'yyyy-MM-dd HH:mm:ss')",
        "> Project root: $ProjectRoot",
        '',
        '| name | description | path |',
        '| --- | --- | --- |'
    )
    foreach ($item in $Items) {
        $desc = $item.Description -replace '\|', '\|' -replace "`r?`n", ' '
        $lines += "| $($item.Name) | $desc | $($item.Path) |"
    }
    Set-Content -LiteralPath $IndexPath -Value ($lines -join "`n") -Encoding UTF8
}

function Get-SkillSourceFiles {
    param([string]$ProjectRoot)

    $sources = @()
    $skillsRoot = Join-Path $ProjectRoot 'skills'
    if (Test-Path $skillsRoot) {
        $sources += Get-ChildItem -Path $skillsRoot -Filter 'SKILL.md' -Recurse -File -ErrorAction SilentlyContinue |
            Where-Object { $_.FullName -notmatch $excludePathPattern }
    }
    $cursorSkills = Join-Path $ProjectRoot '.cursor\skills'
    if (Test-Path $cursorSkills) {
        $sources += Get-ChildItem -Path $cursorSkills -Filter 'SKILL.md' -Recurse -File -ErrorAction SilentlyContinue
    }
    return $sources
}

function Build-SkillsCatalog {
    param([string]$ProjectRoot)

    $entries = @(Get-SkillSourceFiles -ProjectRoot $ProjectRoot | ForEach-Object {
            $relative = $_.FullName.Substring($ProjectRoot.Length).TrimStart('\', '/').Replace('\', '/')
            $content = Get-Content -LiteralPath $_.FullName -Raw -Encoding UTF8
            $name = Get-FrontmatterField -Content $content -Field 'name'
            $description = Get-FrontmatterField -Content $content -Field 'description'
            if (-not $name) { $name = Split-Path (Split-Path $relative -Parent) -Leaf }
            if (-not $description) { $description = '(no description in frontmatter)' }
            [pscustomobject]@{
                Name        = $name
                Description = $description
                Path        = $relative
                SkillDir    = $_.DirectoryName
                SkillFile   = $_.FullName
            }
        })

    $deduped = @{}
    foreach ($item in ($entries | Sort-Object { $_.Path.Length }, Path)) {
        if (-not $deduped.ContainsKey($item.Name)) {
            $deduped[$item.Name] = $item
        }
    }
    return @($deduped.Values | Sort-Object Name)
}

function Build-ContextText {
    param(
        [string]$ProjectRoot,
        [array]$Items,
        [string]$HookLabel
    )
    $lines = @(
        "## Project skills ($HookLabel)",
        "Project root: ``$ProjectRoot``",
        "Total: $($Items.Count) skills under skills/.",
        '',
        '**Required workflow (before replying or using tools):**',
        '1. Read the skills index at .cursor/skills-index.md (or .claude/.codex copy).',
        '2. Semantically match the user request to each skill name/description.',
        '3. For every applicable skill, Read the full SKILL.md and follow it strictly.',
        '4. Mention enabled skill names in one short sentence at the start of the reply.',
        '5. Priority: user instruction > project skill > built-in skill > default behavior.',
        ''
    )
    foreach ($item in $Items) {
        $lines += "- **$($item.Name)**: $($item.Description) -> ``$($item.Path)``"
    }
    return ($lines -join "`n")
}

$projectRoot = Find-ProjectRootWithSkills -SeedDir $StartDir
if (-not $projectRoot) {
    exit 0
}

$items = Build-SkillsCatalog -ProjectRoot $projectRoot
if ($items.Count -eq 0) {
    exit 0
}

$generator = 'scripts/hooks/scan-project-skills.ps1'
Write-SkillsIndex -ProjectRoot $projectRoot -Items $items -IndexPath (Join-Path $projectRoot '.cursor\skills-index.md') -GeneratorLabel $generator
Write-SkillsIndex -ProjectRoot $projectRoot -Items $items -IndexPath (Join-Path $projectRoot '.claude\skills-index.md') -GeneratorLabel $generator
Write-SkillsIndex -ProjectRoot $projectRoot -Items $items -IndexPath (Join-Path $projectRoot '.codex\skills-index.md') -GeneratorLabel $generator

$hookLabel = if ($HookEvent -ne 'Plain') { $HookEvent } else { 'scan' }
$context = Build-ContextText -ProjectRoot $projectRoot -Items $items -HookLabel $hookLabel

[Console]::OutputEncoding = [System.Text.Encoding]::UTF8

switch ($OutputFormat) {
    'Cursor' {
        @{ additional_context = $context } | ConvertTo-Json -Compress
    }
    'Claude' {
        $eventName = if ($HookEvent -eq 'Plain') { 'SessionStart' } else { $HookEvent }
        @{
            hookSpecificOutput = @{
                hookEventName      = $eventName
                additionalContext  = $context
            }
        } | ConvertTo-Json -Compress -Depth 5
    }
    'Codex' {
        Write-Output $context
    }
    default {
        Write-Output $context
    }
}

exit 0
